services:
  - type: web
    name: sudoku-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        value: mongodb+srv://root:example@cluster0.mongodb.net/sudoku?retryWrites=true&w=majority
    regions:
      - oregon
